// Tense system types
export type TenseSystem = "infectum" | "perfectum"

export type InfectumTense = "present" | "imperfect" | "future"
export type PerfectumTense = "perfect" | "pluperfect" | "futurePerfect"

export type LatinTense = InfectumTense | PerfectumTense

export type LatinVerb = {
  firstPerson: string
  secondPerson: string
  infinitive: string
  perfectStem?: string // For perfectum tenses (e.g., amav- for amare)
  supine?: string // For compound perfect tenses
  meaning: string
  conjugation: 1 | 2 | 3 | 4 | "irregular" | string
  // Infectum tenses (action not completed)
  presentConjugation?: [string, string, string, string, string, string]
  imperfectConjugation?: [string, string, string, string, string, string]
  futureConjugation?: [string, string, string, string, string, string]
  // Perfectum tenses (action completed)
  perfectConjugation?: [string, string, string, string, string, string]
  pluperfectConjugation?: [string, string, string, string, string, string]
  futurePerfectConjugation?: [string, string, string, string, string, string]
  isCompound?: boolean
  category?: string
}

// Tense metadata for UI
export const TENSE_INFO = {
  // Infectum - actions not completed (WHITE theme)
  infectum: {
    label: "Infectum",
    description: "Actions non accomplies",
    theme: "light" as const,
    tenses: {
      present: {
        label: "Présent",
        description: "Action actuelle",
        example: "amo, amas, amat...",
        endings: "-o, -s, -t, -mus, -tis, -nt"
      },
      imperfect: {
        label: "Imparfait",
        description: "Action passée continue",
        example: "amabam, amabas, amabat...",
        endings: "-bam, -bas, -bat, -bamus, -batis, -bant"
      },
      future: {
        label: "Futur",
        description: "Action à venir",
        example: "amabo, amabis, amabit...",
        endings: "-bo, -bis, -bit, -bimus, -bitis, -bunt"
      }
    }
  },
  // Perfectum - actions completed (BLACK theme)
  perfectum: {
    label: "Perfectum",
    description: "Actions accomplies",
    theme: "dark" as const,
    tenses: {
      perfect: {
        label: "Parfait",
        description: "Action passée achevée",
        example: "amavi, amavisti, amavit...",
        endings: "-i, -isti, -it, -imus, -istis, -erunt"
      },
      pluperfect: {
        label: "Plus-que-parfait",
        description: "Action antérieure au passé",
        example: "amaveram, amaveras, amaverat...",
        endings: "-eram, -eras, -erat, -eramus, -eratis, -erant"
      },
      futurePerfect: {
        label: "Futur antérieur",
        description: "Action future achevée",
        example: "amavero, amaveris, amaverit...",
        endings: "-ero, -eris, -erit, -erimus, -eritis, -erint"
      }
    }
  }
}

// Helper to get conjugation key from tense
export function getConjugationKey(tense: LatinTense): keyof LatinVerb {
  const map: Record<LatinTense, keyof LatinVerb> = {
    present: "presentConjugation",
    imperfect: "imperfectConjugation",
    future: "futureConjugation",
    perfect: "perfectConjugation",
    pluperfect: "pluperfectConjugation",
    futurePerfect: "futurePerfectConjugation"
  }
  return map[tense]
}

// Helper to get tense system from tense
export function getTenseSystem(tense: LatinTense): TenseSystem {
  if (tense === "present" || tense === "imperfect" || tense === "future") {
    return "infectum"
  }
  return "perfectum"
}

// Fallback verbs are no longer needed - all generated by LLM
export const LATIN_VERBS: LatinVerb[] = []
